image: python:3.12

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test:
  stage: test
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install -r requirements-test.txt
  script:
    - chmod +x ./pep8.sh
    - ./pep8.sh
    - tox
