# Generated by Django 2.2.4 on 2019-09-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webproxy',
            options={'verbose_name_plural': 'web proxies'},
        ),
    ]
