# Generated by Django 2.2.4 on 2020-02-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_auto_20191125_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('source', 'guid'), ('source', 'slug')},
        ),
    ]
