# Generated by Django 2.2.4 on 2021-07-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_auto_20200720_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enclosure',
            name='href',
            field=models.CharField(max_length=2000),
        ),
    ]
