# Generated by Django 2.2.4 on 2022-02-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_auto_20210715_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_created',
            field=models.DateTimeField(blank=True, help_text='Datetime of most recent post.', null=True),
        ),
    ]
