# Generated by Django 2.2.4 on 2022-02-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_source_last_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_created',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datetime of most recent post.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
