# Generated by Django 3.2 on 2024-08-11 02:35
import uuid

from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    Post = apps.get_model('feeds', 'Post')
    total = Post.objects.count()
    for i, post in enumerate(Post.objects.all(), 1):
        if i == 1 or not i % 1000 or i == total:
            percent = int(round(i / total * 100))
            print(f'Processing {i} of {total}: {percent}%')
        post.uuid = uuid.uuid4()
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0019_auto_20220214_1026'),
    ]

    operations = [
        # Step 1: Add the UUID field without unique constraint and with null=True
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(
                default=None,
                editable=False,
                null=True,
                help_text='A semi-secret ID to use for internal purposes. Do not publicly expose so that it is associated with the name.'
            ),
        ),
        # Step 2: Populate the UUID field with unique values
        migrations.RunPython(generate_unique_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Alter the field to set unique=True and null=False
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(
                editable=False,
                unique=True,
                help_text='A semi-secret ID to use for internal purposes. Do not publicly expose so that it is associated with the name.'
            ),
        ),
    ]
