# Generated by Django 3.2 on 2024-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_auto_20240813_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lucene_index_actual',
            field=models.BooleanField(default=False, editable=False, help_text='The index state we currently have. True=indexed for search.'),
        ),
        migrations.AddField(
            model_name='post',
            name='lucene_index_target',
            field=models.BooleanField(default=False, help_text='The index state we want. True=indexed for search.'),
        ),
        migrations.AddField(
            model_name='source',
            name='lucene_index_actual',
            field=models.BooleanField(default=False, editable=False, help_text='The index state we currently have. True=indexed for search.'),
        ),
        migrations.AddField(
            model_name='source',
            name='lucene_index_target',
            field=models.BooleanField(default=False, help_text='The index state we want. True=indexed for search.'),
        ),
    ]
