# Generated by Django 3.2 on 2024-08-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_auto_20240819_0849'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['lucene_index_target', 'lucene_index_actual'], name='feeds_post_lucene__aae4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['lucene_index_target', 'lucene_index_actual'], name='feeds_sourc_lucene__641cba_idx'),
        ),
    ]
