# Generated by Django 5.1 on 2024-09-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_auto_20240819_1803'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created'], name='feeds_post_created_1b6fad_idx'),
        ),
        # migrations.AddIndex(
        # model_name='post',
        # index=django.contrib.postgres.indexes.GinIndex(fields=['body'], name='feeds_post_body_2498e9_gin'),
        # ),
        migrations.AddConstraint(
            model_name='mediacontent',
            constraint=models.UniqueConstraint(fields=('post', 'url'), name='unique_post_url'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('source', 'slug'), name='unique_source_slug'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('source', 'guid'), name='unique_source_guid'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE INDEX feeds_post_body_gin_idx ON feeds_post USING gin(to_tsvector('english', body));
            """,
            reverse_sql="""
                DROP INDEX feeds_post_body_gin_idx;
            """,
        ),
    ]
