# Generated by Django 5.1 on 2025-05-06 20:46

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0024_alter_mediacontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediacontent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='A semi-secret ID to use for internal purposes. Do not publicly expose so that it is associated with the name.',
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='source',
            name='due_poll',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 5, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_change',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 5, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_success',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 5, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='A semi-secret ID to use for internal purposes. Do not publicly expose so that it is associated with the name.',
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='webproxy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
