# Generated by Django 5.1 on 2025-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0025_alter_mediacontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='archive_to_s3',
            field=models.BooleanField(default=False, help_text='If set, uploads all post media files to the pre-configured S3 bucket.'),
        ),
        migrations.AddField(
            model_name='source',
            name='extract_from_raw_html',
            field=models.BooleanField(default=False, help_text='If checked, extracts using the raw html parsing fields below.'),
        ),
        migrations.AddField(
            model_name='source',
            name='html_item_class',
            field=models.CharField(blank=True, help_text='CSS path expression to each post list item in the raw HTML.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='html_item_date_class',
            field=models.CharField(
                blank=True, help_text="CSS path expression to each post list item's published date in the raw HTML.", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='html_item_link_class',
            field=models.CharField(blank=True, help_text="CSS path expression to each post list item's page link in the raw HTML.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='html_result_getter',
            field=models.CharField(blank=True, help_text='Command to call given a URL to download the actual media file.', max_length=255, null=True),
        ),
    ]
