# Generated by Django 5.1 on 2025-05-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0026_source_archive_to_s3_source_extract_from_raw_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='html_item_title_class',
            field=models.CharField(blank=True, help_text="CSS path expression to each post list item's page title in the raw HTML.", max_length=255, null=True),
        ),
    ]
