# Generated by Django 5.1 on 2025-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0027_source_html_item_title_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='update',
            field=models.BooleanField(default=True, help_text='If set, periodically pulls updates from feed URL.'),
        ),
        migrations.AlterField(
            model_name='source',
            name='live',
            field=models.BooleanField(default=True, help_text='If set, shows source and posts publicaly.'),
        ),
    ]
