# Generated by Django 5.1 on 2025-05-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0028_source_update_alter_source_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='extract_from_raw_html_page_key',
            field=models.CharField(
                blank=True,
                help_text='Optional URL key to denote page. If given, the URL will be iterated over, substituting N pages in this variable.',
                max_length=100,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='extract_from_raw_html_page_max',
            field=models.IntegerField(default=10, help_text='Maximum page number to iterate to.'),
        ),
    ]
